import type { ShopProduct } from "@/lib/shop";

export const SEARCH_RESULT_COUNT = 124;

export type SearchChip = {
  id: string;
  label: string;
  count: number;
};

export const searchChips: SearchChip[] = [
  { id: "all", label: "All", count: 124 },
  { id: "iphones", label: "iPhones", count: 124 },
  { id: "accessories", label: "Accessories", count: 42 },
  { id: "cases", label: "Cases", count: 28 },
  { id: "chargers", label: "Chargers", count: 16 },
  { id: "protectors", label: "Screen Protectors", count: 14 },
];

export const searchCategories = [
  { id: "iphones", label: "iPhones", count: 124 },
  { id: "accessories", label: "Accessories", count: 42 },
  { id: "cases", label: "Cases", count: 28 },
  { id: "chargers", label: "Chargers", count: 16 },
  { id: "protectors", label: "Screen Protectors", count: 14 },
  { id: "audio", label: "Audio", count: 8 },
  { id: "other", label: "Other", count: 6 },
] as const;

export const searchModels = [
  { id: "iphone-16-pro-max", label: "iPhone 16 Pro Max", count: 18 },
  { id: "iphone-16-pro", label: "iPhone 16 Pro", count: 20 },
  { id: "iphone-16", label: "iPhone 16", count: 16 },
  { id: "iphone-15", label: "iPhone 15", count: 24 },
  { id: "iphone-14", label: "iPhone 14", count: 18 },
  { id: "iphone-13", label: "iPhone 13", count: 12 },
  { id: "iphone-12", label: "iPhone 12", count: 8 },
  { id: "others", label: "Others", count: 6 },
] as const;

export const searchConditions = [
  { id: "New", label: "New", count: 92 },
  { id: "Used", label: "Used", count: 28 },
  { id: "Refurbished", label: "Refurbished", count: 4 },
] as const;

export const searchStorage = [
  { id: "128GB", label: "128GB", count: 40 },
  { id: "256GB", label: "256GB", count: 52 },
  { id: "512GB", label: "512GB", count: 24 },
  { id: "1TB", label: "1TB", count: 8 },
] as const;

export const searchColors = [
  { id: "black", hex: "#2b2b2d", label: "Black" },
  { id: "silver", hex: "#e8e8ea", label: "Silver" },
  { id: "blue", hex: "#7aa2ff", label: "Blue" },
  { id: "pink", hex: "#f3c6d3", label: "Pink" },
  { id: "starlight", hex: "#f0e6d6", label: "Starlight" },
] as const;

export const searchBrands = [
  { id: "Apple", label: "Apple", count: 124 },
  { id: "Others", label: "Others", count: 0 },
] as const;

export type SearchProduct = ShopProduct & {
  chip: SearchChip["id"];
  model?: string;
  storage?: string;
  color?: string;
};

export const searchProducts: SearchProduct[] = [
  {
    id: "iphone-16-pro-max",
    name: "iPhone 16 Pro Max",
    specs: "256GB • Black Titanium • New",
    price: 12500,
    rating: 4.9,
    reviews: 128,
    image: "/images/iphones-hero.png",
    imageAlt: "iPhone 16 Pro Max Black Titanium",
    badge: "Bestseller",
    category: "iphones",
    condition: "New",
    brand: "Apple",
    href: "/products/iphone-16-pro-max",
    chip: "iphones",
    model: "iphone-16-pro-max",
    storage: "256GB",
    color: "black",
  },
  {
    id: "iphone-16-pro",
    name: "iPhone 16 Pro",
    specs: "256GB • Natural Titanium • New",
    price: 11800,
    rating: 4.8,
    reviews: 95,
    image: "/images/iphones-hero.png",
    imageAlt: "iPhone 16 Pro Natural Titanium",
    badge: "New",
    category: "iphones",
    condition: "New",
    brand: "Apple",
    href: "/products/iphone-16-pro",
    chip: "iphones",
    model: "iphone-16-pro",
    storage: "256GB",
    color: "silver",
  },
  {
    id: "iphone-16",
    name: "iPhone 16",
    specs: "128GB • Ultramarine • New",
    price: 9000,
    rating: 4.7,
    reviews: 72,
    image: "/images/iphones-lineup.png",
    imageAlt: "iPhone 16 Ultramarine",
    badge: "New",
    category: "iphones",
    condition: "New",
    brand: "Apple",
    href: "/products/iphone-16",
    chip: "iphones",
    model: "iphone-16",
    storage: "128GB",
    color: "blue",
  },
  {
    id: "iphone-15",
    name: "iPhone 15",
    specs: "128GB • Pink • New",
    price: 7900,
    compareAt: 8900,
    rating: 4.6,
    reviews: 64,
    image: "/images/iphones-lineup.png",
    imageAlt: "iPhone 15 Pink",
    badge: "Sale",
    category: "iphones",
    condition: "New",
    brand: "Apple",
    href: "/products/iphone-15",
    chip: "iphones",
    model: "iphone-15",
    storage: "128GB",
    color: "pink",
  },
  {
    id: "iphone-14",
    name: "iPhone 14",
    specs: "128GB • Midnight • Used (Like New)",
    price: 5300,
    rating: 4.6,
    reviews: 62,
    image: "/images/iphones-hero.png",
    imageAlt: "iPhone 14 Midnight",
    badge: "Popular",
    category: "iphones",
    condition: "Used",
    brand: "Apple",
    href: "/products/iphone-14",
    chip: "iphones",
    model: "iphone-14",
    storage: "128GB",
    color: "black",
  },
  {
    id: "iphone-13",
    name: "iPhone 13",
    specs: "128GB • Starlight • Used",
    price: 4200,
    rating: 4.5,
    reviews: 80,
    image: "/images/iphones-lineup.png",
    imageAlt: "iPhone 13 Starlight",
    badge: "Bestseller",
    category: "iphones",
    condition: "Used",
    brand: "Apple",
    href: "/products/iphone-13",
    chip: "iphones",
    model: "iphone-13",
    storage: "128GB",
    color: "starlight",
  },
  {
    id: "iphone-12",
    name: "iPhone 12",
    specs: "64GB • Black • Used",
    price: 3100,
    rating: 4.4,
    reviews: 51,
    image: "/images/iphones-hero.png",
    imageAlt: "iPhone 12 Black",
    category: "iphones",
    condition: "Used",
    brand: "Apple",
    href: "/products/iphone-12",
    chip: "iphones",
    model: "iphone-12",
    color: "black",
  },
  {
    id: "iphone-16-plus",
    name: "iPhone 16 Plus",
    specs: "256GB • White • New",
    price: 10800,
    rating: 4.8,
    reviews: 36,
    image: "/images/iphones-lineup.png",
    imageAlt: "iPhone 16 Plus White",
    badge: "New",
    category: "iphones",
    condition: "New",
    brand: "Apple",
    href: "/products/iphone-16-plus",
    chip: "iphones",
    model: "others",
    storage: "256GB",
    color: "silver",
  },
  {
    id: "magsafe-charger",
    name: "Apple MagSafe Charger",
    specs: "White • New",
    price: 320,
    rating: 4.7,
    reviews: 20,
    image: "/images/accessories-hero.png",
    imageAlt: "Apple MagSafe Charger",
    category: "accessories",
    condition: "New",
    brand: "Apple",
    href: "/products/magsafe-charger",
    chip: "chargers",
    color: "silver",
  },
  {
    id: "apple-20w",
    name: "Apple 20W USB-C Adapter",
    specs: "White • New",
    price: 280,
    rating: 4.6,
    reviews: 90,
    image: "/images/accessories-hero.png",
    imageAlt: "Apple 20W USB-C power adapter",
    category: "accessories",
    condition: "New",
    brand: "Apple",
    href: "/products/apple-20w",
    chip: "chargers",
    color: "silver",
  },
  {
    id: "iphone-silicone-case",
    name: "iPhone Silicone Case",
    specs: "For iPhone 16 • Black",
    price: 350,
    rating: 4.7,
    reviews: 72,
    image: "/images/accessories-hero.png",
    imageAlt: "Black iPhone silicone case",
    category: "accessories",
    condition: "New",
    brand: "Apple",
    href: "/products/iphone-silicone-case",
    cta: "Choose Options",
    chip: "cases",
    color: "black",
  },
  {
    id: "screen-protector",
    name: "Tempered Glass Screen Protector",
    specs: "For iPhone 16 • 2-Pack",
    price: 80,
    rating: 4.5,
    reviews: 120,
    image: "/images/accessories-hero.png",
    imageAlt: "Tempered glass screen protector 2-pack",
    category: "accessories",
    condition: "New",
    brand: "Apple",
    href: "/products/screen-protector",
    chip: "protectors",
  },
];
